archivo<-read.csv("~/Downloads/Nutritional_food.csv",sep = ",")
View(archivo)
#attach(archivo)
summary(archivo)
mean(calories)
median(calories)
#install.packages("modeest")
#library(modeest)
var(calories)
plot(calories,serving_size)
cor(calories,serving_size)

plot(calories,fat)
cor(calories,fat)
